### ISSUE TITLE
044fd19b75e4237f7108c56e83b1b91c8ae98420 broke everything :)

### ISSUE THREAD

**Issue by cmutel** [fjuniorr/flowmapper-ci#10]
The main branch of `flowmapper` is still expecting a `toml` file, so we get this error:

```python
  File "/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tomllib/_parser.py", line 404, in parse_key_part
    raise suffixed_err(src, pos, "Invalid initial character for a key part")

tomllib.TOMLDecodeError: Invalid initial character for a key part (at line 1, column 11)
```

**Comment by fjuniorr** [comment]
Sorry for the unsynchronized changes in the repos @cmutel. I've merged https://github.com/fjuniorr/flowmapper/pull/48 to use the [new python config file](https://github.com/fjuniorr/flowmapper-ci/blob/main/config/simapro-ecoinvent.py) to make it easier for us to test things and we can revert things after if needed.

**Comment by cmutel** [comment]
It's OK, I'm not complaining, just making sure you saw this error. Close if you think this is fixed.
