### ISSUE TITLE
Missing `xmltodict` dependency in `requirements.txt`

### ISSUE THREAD

**Issue by cmutel** [fjuniorr/flowmapper-ci#2]

**Comment by cmutel** [comment]
Also need to add `openpyxl`

**Comment by fjuniorr** [comment]
Thanks! I've added `xmltodict` but `openpyxl` will not be needed because I [removed the simapro flowlists that don't have the full context](https://github.com/fjuniorr/flowmapper/issues/13#issuecomment-1819779766).
