### ISSUE TITLE
Output should also write unmatched flows in a separate file

### ISSUE THREAD

**Issue by cmutel** [fjuniorr/flowmapper-ci#7]
This is necessary to know which flows to prioritize for future strategy development.

**Comment by fjuniorr** [comment]
This is done after https://github.com/fjuniorr/flowmapper/pull/38 @cmutel.

I've added flags to the CLI to control which original flows should be written to files (both matched and unmatched):

```bash
flowmapper map --help
# Usage: flowmapper map [OPTIONS] SOURCE TARGET

#   Generate mappings between elementary flows lists

# Arguments:
#   SOURCE  Path to source flowlist  [required]
#   TARGET  Path to target flowlist  [required]

# Options:
#   --fields PATH                   Relationship between fields in source and
#                                   target flowlists  [required]
#   --output-dir PATH               Directory to save mapping and diagnostics
#                                   files  [default: .]
#   --format [all|glad|randonneur]  Mapping file output format  [default: all]
#   --unmatched-source / --no-unmatched-source
#                                   Write original source unmatched flows into
#                                   separate file?  [default: unmatched-source]
#   --unmatched-target / --no-unmatched-target
#                                   Write original target unmatched flows into
#                                   separate file?  [default: unmatched-target]
#   --matched-source / --no-matched-source
#                                   Write original source matched flows into
#                                   separate file?  [default: no-matched-source]
#   --matched-target / --no-matched-target
#                                   Write original target matched flows into
#                                   separate file?  [default: no-matched-target]
#   --help                          Show this message and exit.
```

Should I go ahead and create a github actions workflow to generate something similar to [status.md](https://github.com/brightway-lca/simapro_ecoinvent_elementary_flows/blob/main/status.md) when new versions of `flowmapper` are pushed to `main`?

**Comment by cmutel** [comment]
> Should I go ahead and create a github actions workflow to generate something similar to [status.md](https://github.com/brightway-lca/simapro_ecoinvent_elementary_flows/blob/main/status.md) when new versions of flowmapper are pushed to main?

Yes, this would make a big difference, and be very helpful!

**Comment by fjuniorr** [comment]
Got it! I'm closing this and tracking the status generation in https://github.com/fjuniorr/flowmapper-ci/issues/8
